services:
  db:
    image: mysql:8.3
    container_name: timeless_shop_sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: timeless.admin
      MYSQL_PASSWORD: 190er
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: